Personlista/Models/PersonRegister/Commands/Create.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Personlista.Models
{
    public static partial class PersonRegister
    {
        /// <summary>
        /// 
        /// </summary>
        public static string Create()
        {
            //todo: lookup count of personregister and add new unique id
            return "";
        }
    }
}

Personlista/Models/PersonRegister/Commands/Read.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Xml.Serialization;

namespace Personlista.Models
{
    [XmlRoot(ElementName = "ArrayOfPerson")]
    public class ArrayOfPerson
    {
        [XmlElement(ElementName = "Person")]
        public List<Person> Persons { get; set; }
    }

    public class Person
    {
        [XmlElement(ElementName = "ID")]
        public int Id { get; set; }

        [XmlElement(ElementName = "Firstname")]
        public string Firstname { get; set; }

        [XmlElement(ElementName = "Lastname")]
        public string Lastname { get; set; }

        [XmlElement(ElementName = "Socialnumber")]
        public string Socialnumber { get; set; }

        [XmlElement(ElementName = "PersonCategory")]
        public string PersonCategory { get; set; }
    }

    public static class XmlFileData
    {
        /// <summary>
        /// Get data from xml file
        /// </summary>
        /// <returns></returns>
        public static ArrayOfPerson ReadXmlFile()
        {
            var path = HttpContext.Current.Server.MapPath("/Content/Files/personer.xml");

            var xmlSerializer = new XmlSerializer(typeof(ArrayOfPerson));

            var arrayOfPerson = default(ArrayOfPerson);
            using (var stringReader = new StringReader(File.ReadAllText(path)))
            {
                arrayOfPerson = (ArrayOfPerson)xmlSerializer.Deserialize(stringReader);
            }

            return arrayOfPerson;
        }
    }
}

Personlista/Models/PersonRegister/Commands/Save.cs
using System.Linq;
using System.Web;
using System.Xml.Linq;

namespace Personlista.Models
{
    public static partial class PersonRegister
    {
        /// <summary>
        /// Save to file
        /// </summary>
        public static void Save(CreateRequest createRequest)
        {
            var arrayOfPersons = XmlFileData.ReadXmlFile();

            //Create new id
            var personId = arrayOfPersons.Persons.Count() + 1;

            //Get file
            var path = HttpContext.Current.Server.MapPath("/Content/Files/personer.xml");
            XDocument doc = XDocument.Load(path);
            XElement root = new XElement("ArrayOfPerson");

            //Add new person
            foreach (var person in createRequest.ListOfPersons)
            {
                doc.Root.Add(
                    new XElement("Person",
                        new XElement("ID", personId),
                        new XElement("Firstname", person.FirstName),
                        new XElement("Lastname", person.LastName),
                        new XElement("Socialnumber", person.PersonNumber),
                        new XElement("PersonCategory", person.PersonType)
                        ));
                doc.Save(path);
            }
        }
    }

}

Personlista/Models/PersonRegister/Data/CreateRequest.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Personlista.Models
{
    /// <summary>
    /// Search request to filter list
    /// </summary>
    public class CreateRequest
    {
        /// <summary>
        /// SearchRequest
        /// </summary>
        public SearchRequest SearchRequest { get; set; }

        /// <summary>
        /// Persons to be created
        /// </summary>
        public CreatedPerson CreatedPerson { get; set; }

        /// <summary>
        /// List of persons to be created
        /// </summary>
        public List<CreatedPerson> ListOfPersons { get; set; }
    }

    /// <summary>
    /// Person to be created listdata
    /// </summary>
    public class CreatedPerson
    {
        /// <summary>
        /// FirstName
        /// </summary>
        public string FirstName { get; set; }

        /// <summary>
        /// LastName
        /// </summary>
        public string LastName { get; set; }

        /// <summary>
        /// PersonNumber
        /// </summary>
        public string PersonNumber { get; set; }

        /// <summary>
        /// PersonType
        /// </summary>
        public string PersonType { get; set; }
    }
}

Personlista/Models/PersonRegister/Data/PersonRegisterListData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Personlista.Models
{
    public static partial class PersonRegister
    {
        /// <summary>
        /// 
        /// </summary>
        public class PersonRegisterListData
        {
            /// <summary>
            /// List of persons 
            /// </summary>
            public List<Person> Persons { get; set; }

            /// <summary>
            /// Count of the found persons in list
            /// </summary>
            public int ListCount { get; set; }

            /// <summary>
            /// Count of pages
            /// </summary>
            public int PageCount { get; set; }

            /// <summary>
            /// The current page number in pageination
            /// </summary>
            public int CurrentPage { get; set; }

            /// <summary>
            /// The first page number in pageination
            /// </summary>
            public int FirstPage { get; set; }

            /// <summary>
            /// The last page number in pageination
            /// </summary>
            public int LastPage { get; set; }
        }
    }
}

Personlista/Models/PersonRegister/Data/SearchRequest.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Personlista.Models
{

    /// <summary>
    /// Search request to filter list
    /// </summary>
    public class SearchRequest
    {
        /// <summary>
        /// Search in list
        /// </summary>
        public string SearchString { get; set; }

        /// <summary>
        /// The number of item to display before splitting to new page
        /// </summary>
        public DisplayNumber DisplayNumber { get; set; }

        /// <summary>
        /// The page number
        /// </summary>
        public int? PageNumber { get; set; }
    }

    public enum DisplayNumber
    {
        Display10 = 0,
        Display50,
        Display100
    }

}

Personlista/Models/PersonRegister/Query/GetPersonRegisterList.cs
using System.Linq;

namespace Personlista.Models
{
    /// <summary>
    /// Repository for register of persons
    /// </summary>
    public static partial class PersonRegister
    {
        /// <summary>
        /// Get list of persons
        /// </summary>
        public static PersonRegisterListData GetPersonRegisterList(SearchRequest searchRequest)
        {
            var result = new PersonRegisterListData();

            //Get data
            var arrayOfPersons = XmlFileData.ReadXmlFile();
            var personList = arrayOfPersons.Persons.Where(x => 
                !string.IsNullOrEmpty(x.Firstname) &&
                !string.IsNullOrEmpty(x.Lastname) && 
                !string.IsNullOrEmpty(x.PersonCategory) &&
                !string.IsNullOrEmpty(x.Socialnumber));

            //Filter by search string in list
            if (!string.IsNullOrEmpty(searchRequest.SearchString))
            {
                personList = personList.Where(x => 
                    x.Firstname.ToLower().Contains(searchRequest.SearchString.ToLower()) ||
                    x.Lastname.ToLower().Contains(searchRequest.SearchString.ToLower()) ||
                    x.PersonCategory.ToLower().Contains(searchRequest.SearchString.ToLower()) ||
                    x.Socialnumber.ToLower().Contains(searchRequest.SearchString.ToLower())).ToList();
            }

            //Filter number of items per page
            var take = 0;
            switch (searchRequest.DisplayNumber)
            {
                case DisplayNumber.Display50:
                    take = 50;
                    break;
                case DisplayNumber.Display100:
                    take = 100;
                    break;
                default:
                    take = 10;
                    break;
            }

            //Number of persons found
            var foundPersons = personList.Count();
            result.ListCount = foundPersons;

            //Number of pages
            var numberOfPages = (foundPersons + take - 1) / take;
            result.PageCount = numberOfPages;

            //Pagination
            var currentPage = searchRequest.PageNumber.HasValue ? searchRequest.PageNumber.Value : 1;
            var startPage = currentPage - 5;
            var endPage = currentPage + 4;

            if (startPage <= 0)
            {
                endPage -= (startPage - 1);
                startPage = 1;
            }

            if (endPage > numberOfPages)
            {
                endPage = numberOfPages;

                if (endPage > 10)
                {
                    startPage = endPage - 9;
                }
            }

            result.CurrentPage = currentPage;
            result.FirstPage = startPage;
            result.LastPage = endPage;


            //Return list
            var skip = (currentPage - 1) * take;

            result.Persons = personList.Skip(skip).Take(take).ToList();
            return result;
        }
    }
}

Personlista/Controllers/PersonRegisterController.cs
using Personlista.Models;
using Personlista.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Personlista.Controllers
{
    public class PersonRegisterController : Controller
    {
        /// <summary>
        /// Get person register view
        /// </summary>
        /// <returns></returns>
        public ActionResult PersonRegisterList()
        {
            var viewData = new PersonRegisterListViewData();
            viewData.SearchRequest = new SearchRequest { DisplayNumber = DisplayNumber.Display10 };
            viewData.CreateRequest = new CreateRequest();

            return View(viewData);
        }

        /// <summary>
        /// Get person register list in partial view
        /// </summary>
        /// <returns></returns>
        public PartialViewResult PersonRegisterListResult(SearchRequest searchRequest)
        {
            var viewData = GetPersonListViewData(searchRequest);

            return PartialView(viewData);
        }

        private PersonRegisterListResultViewData GetPersonListViewData(SearchRequest searchRequest)
        {
            var viewData = new PersonRegisterListResultViewData();

            var list = PersonRegister.GetPersonRegisterList(searchRequest);

            viewData.PersonList = list.Persons;
            viewData.ListCount = list.ListCount;
            viewData.PageCount = list.PageCount;
            viewData.CurrentPage = list.CurrentPage;
            viewData.FirstPage = list.FirstPage;
            viewData.LastPage = list.LastPage;
            viewData.SearchRequest = searchRequest;

            return viewData;
        }


        /// <summary>
        /// Save one person
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SavePerson(CreateRequest createRequest)
        {
            createRequest.ListOfPersons = new List<CreatedPerson>()
            {
                new CreatedPerson
                {
                  FirstName = createRequest.CreatedPerson.FirstName,
                  LastName = createRequest.CreatedPerson.LastName,
                  PersonNumber = createRequest.CreatedPerson.PersonNumber,
                  PersonType = createRequest.CreatedPerson.PersonType
                }
            };

            PersonRegister.Save(createRequest);

            var viewData = GetPersonListViewData(new SearchRequest());
            return PartialView("PersonRegisterListResult", viewData);
        }

        /// <summary>
        /// Save all persons
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SaveAllNewPersons(CreateRequest createRequests)
        {
            PersonRegister.Save(createRequests);

            var viewData = GetPersonListViewData(new SearchRequest());
            return PartialView("PersonRegisterListResult", viewData);
        }

    }
}

Personlista/Views/PersonRegister/PersonRegisterList.cshtml
@using Personlista.Models
@model Personlista.ViewModel.PersonRegisterListViewData

@using (Html.BeginForm("PersonRegisterListResult", "PersonRegister", FormMethod.Post, new { role = "form", id = "personSearchForm" }))
{
    <div style="margin-top:30px;">
        <div style="float:left; padding: 15px;">
            <p>Filtrera efter sökord</p>
            @Html.TextBoxFor(model => model.SearchRequest.SearchString, new { id = "searchString", placeholder = "Sök", @class = "filterInput" })
        </div>

        <div style="float:left; padding: 15px;">
            <p>Antal resultat per sida</p>

            <label>
                @Html.RadioButtonFor(model => model.SearchRequest.DisplayNumber, DisplayNumber.Display10, new {@class = "filterInput" })
                10 st
            </label>
            <label>
                @Html.RadioButtonFor(model => model.SearchRequest.DisplayNumber, DisplayNumber.Display50, new { @class = "filterInput" })
                50 st
            </label>
            <label>
                @Html.RadioButtonFor(model => model.SearchRequest.DisplayNumber, DisplayNumber.Display100, new { @class = "filterInput" })
                100 st
            </label>
        </div>

        <button id="saveAllNewPersonsBtn" class="btn btn-success" type="button" style="float:right;">Spara alla nya poster</button>
    </div>

    <div style="clear: both; padding:15px;">
        <p>Lägg till en ny person</p>

        @Html.TextBoxFor(model => model.CreateRequest.CreatedPerson.FirstName, new {id= "CreateFirstName", placeholder = "Förnamn", @class = "createInput" })
        @Html.TextBoxFor(model => model.CreateRequest.CreatedPerson.LastName, new {id = "CreateLastName", placeholder = "Efternamn", @class = "createInput" })
        @Html.TextBoxFor(model => model.CreateRequest.CreatedPerson.PersonNumber, new { id = "CreateSocialSecurityNumber", placeholder = "Personnummer", @class = "createInput" })
        @Html.TextBoxFor(model => model.CreateRequest.CreatedPerson.PersonType, new { id = "CreatePersonType", placeholder = "Persontyp", @class = "createInput" })
        <button id="addPersonBtn" class="btn btn-info" type="button" style="padding:5px;"> Lägg till </button>
    </div>
}

<div id="searchResult" style="clear: both; border: 1px solid #ccc; padding: 15px; margin: 15px;">
    @Html.Action("PersonRegisterListResult", Model.SearchRequest)
</div>

<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="~/scripts/custom/formscript.js"></script>
<script src="~/scripts/custom/createpersonscript.js"></script>

Personlista/Views/PersonRegister/PersonRegisterListResult.cshtml
@model Personlista.ViewModel.PersonRegisterListResultViewData
@{
    var urlOne = @Url.Action("SavePerson", "PersonRegister");
    var urlMany = @Url.Action("SaveAllNewPersons", "PersonRegister");
}

<h3>Lista över påhittade personer</h3>
<p>Antal träffar: @Model.ListCount st</p>

@if (Model.LastPage > 1)
{
    <ul class="pagination">

        @if (Model.CurrentPage > 6)
        {
            <li class="page-item">
                <a class="page-link" data-page-index="1" style="margin-right:15px;"> 1 </a>
            </li>
        }

        @for (int i = Model.FirstPage; i <= Model.LastPage; i++)
        {
            var activePage = i == Model.CurrentPage ? "active" : "";

            <li class="page-item @activePage">
                <a href="#"  class="page-link" data-page-index="@i">@i</a>
            </li>
        }
        @if (Model.LastPage < Model.PageCount)
        {
            <li class="page-item">
                <a class="page-link" data-page-index="@Model.PageCount" style="margin-left:15px;"> @Model.PageCount </a>
            </li>
        }

    </ul>
}


<table id="personTable" data-url-one="@urlOne" data-url-many="@urlMany" style="width: 100%; background-color: #eeeff8;">
    <thead>
        <tr>
            <th width="30%">Namn</th>
            <th width="30%">Personnummer</th>
            <th width="30%">Persontyp</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model.PersonList)
            {
            <tr style="border-top: 1px solid #ccc">
                <td>
                    <p>@item.Id: @item.Firstname @item.Lastname</p>
                </td>
                <td>
                    <p>@item.Socialnumber</p>
                </td>
                <td>
                    <p>@item.PersonCategory</p>
                </td>
                <td>
                    
                </td>
            </tr>
        }
    </tbody>
</table>

<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script>
    //Detect click on page number
    $('.page-link').on('click', function () {
        console.log("page-link");
        var searchRequest = {
            DisplayNumber: $('input[name="SearchRequest.DisplayNumber"]:checked').val(),
            SearchString: $('#searchString').val(),
            PageNumber: $(this).data('page-index')
        }

        setTimeout(function () {
            CallActionAndRefreshData(searchRequest);
        }, 200)
    });
</script>